{% set name = "cp2kdata" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6d886636f49b5738cc02244813ea9496b366c908531b96ab4b8e0b1cddb4be5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - cp2kdata = cp2kdata.cli.cmd:cli

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.24.3
    - scipy >=1.5.4
    - matplotlib-base >=3.3.2
    - ase >=3.20.1
    - cp2k-input-tools
    - dpdata
    - click
    - regex
    - monty
    - pyyaml
    - asciichartpy
    - pycp2k

test:
  imports:
    - cp2kdata
  commands:
    - cp2kdata --help


about:
  home: https://github.com/robinzyb/cp2kdata
  summary: A Small Package to Postprocess Cp2k Output
  license: LGPL-3.0-only
  license_file: LICENSE
  doc_url: https://robinzyb.github.io/cp2kdata/intro.html

extra:
  recipe-maintainers:
    - robinzyb
